swagger: "2.0"
info:
  version: 1.0.0
  title: Resume Server
  description: Resume Server
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification
  - name: Authentication
    description: Authentication API endpoints
  - name: Users
    description: Retrieve and control users

consumes:
  - application/json
produces:
  - application/json

definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

paths:
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification

  # Users

  /users/me:
    get:
      tags:
        - Users
      responses:
        200:
          description: Returns current user profile
        401:
          description: User not authorized

  # OAuth

  /oauth/github:
    get:
      tags:
        - Authentication
      responses:
        200:
          description: OK

  /oauth/github/callback:
    get:
      tags:
        - Authentication
      responses:
        200:
          description: Successful login

  /oauth/logout:
    get:
      tags:
        - Authentication
      responses:
        200:
          description: Logout is successful
