swagger: "2.0"
info:
  version: 1.0.0
  title: server
  description: Resume Server
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification
  - name: Authentication
    description: Authentication API endpoints
  - name: Users
    description: Retrieve and control users

consumes:
  - application/json
produces:
  - application/json

definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

paths:
  /oauth/logout:
    get:
      responses:
        200:
          description: Logout successful
  /users/me:
    get:
      responses:
        200:
          description: Returns current user profile
        401:
          description: User not authorized
  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema:
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification

  /oauth/github:
    get:
      tags:
        - Authentication
      responses:
        200:
          description: OK

  /oauth/github/callback:
    get:
      tags:
        - Authentication
      responses:
        200:
          description: Successful login
